### PR TITLE
Ros2 fixes

### LINKED ISSUE #3: implement message latching for ROS2

### LINKED ISSUE #4: implement subscription throttling for ROS2

### LINKED ISSUE #5: Unify ros.getTopicsWithTypes responses for ROS1 and 2

### LINKED ISSUE #7: ROS: Allow multiple subscribers to same topic
It is sometimes desirable to allow multiple subscribers to the same ROS topic, i.e., have two or more different callbacks triggered for any new message received on that topic. This currently works but unsubscribing is not handle correctly in ROS 2 because of the way rclnodejs implements that. Compare https://github.com/transitiverobotics/transitive-utils/blob/main/ros/ros/ros2.js#L163 and https://github.com/transitiverobotics/transitive-utils/blob/main/ros/ros/ros.js#L118. As can be seen, rclnodejs does not keep track of the subscribers for a topic and can hence not handle the shutting down of them for us, unlike rosnodejs.

The plan of record is to:
- add an event emitter in the ROS2 class,
- in the subscribe function decouple the ros subscription from the callback:
  - the ROS subscribe callback will just emit an event in the event emitter
  - and the callback back to the user will be added as an event listener to that emitter
  - we'll need to update the returned shutdown function to *not* shutdown the subscriber but just remove the event listener, and only if it was the last listener, also shut down the subscription
- the `unsubscribe` function will just shut down the only ROS subscriber we have for the topic and remove all listeners.

### PR DESCRIPTION
**Pull request by jlurgo**
- adds throttling option to ROS2 subscribers
  - needs test 
- adds latching support to ROS2 pub/subs
- getTopicsWithTypes returns {name: topicName, type: topicType } (same fields as ROS1 response
- allows multiple subscribers for same ROS2 topic, handling independent subscribers shutdown

closes #3 
closes #4 
closes #5 
closes #7

### CODE REVIEW

File: ros/ros/ros2.js [hunk 1]
```diff
@@ -7,8 +7,13 @@ const { getLogger, wait } = require('@transitive-sdk/utils');
 const log = getLogger('ROS2');
 log.setLevel('info');
 
-qos = new rclnodejs.QoS();
-qos.reliability = rclnodejs.QoS.ReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT;
+volatileQos = new rclnodejs.QoS();
+volatileQos.reliability = rclnodejs.QoS.ReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT;
+
+latchingQos = new rclnodejs.QoS();
+latchingQos.reliability = rclnodejs.QoS.ReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_RELIABLE;
```
Comment (chfritz) [inline ros/ros/ros2.js:15]: No, I don't think we can do this, which is the reason why we had the best-effort in place. "Reliable" is not compatible with all publishers, see: https://docs.ros.org/en/rolling/Concepts/Intermediate/About-Quality-of-Service-Settings.html#qos-compatibilities

File: ros/ros/ros2.js [hunk 2]
```diff
@@ -137,48 +146,92 @@ class ROS2 {
...
+        }
+        _onMessage(msg);
+      }
+    );  
+
+    if(!this.subscriptions[topic]){
+      this.subscriptions[topic] = []
+    }
+    this.subscriptions[topic].push(volatileSub);
+    this.subscriptions[topic].push(latchingSub);
```
Comment (chfritz) [inline ros/ros/ros2.js]: Are you sure changing the schema of `this.subscriptions[topic]` from a single value to array does not cause issues elsewhere? I'd rather just keep the volatile subscriber in that variable, and only store the latching one locally, which seems to be all the need because it's really only temporary. Would that work?

File: ros/ros/ros2.js [hunk 3]
```diff
@@ -137,48 +146,92 @@ class ROS2 {
...
+        _onMessage(msg);
+      }
+    );
+
+    const volatileSub = this.node.createSubscription(
+      ros2Type, topic, {qos: volatileQos, ...options}, (msg) => {
+        _destroySub(latchingSub);
+        if (firstLatchedMessage){
+          if(_.isEqual(firstLatchedMessage, msg)){
+            firstLatchedMessage = undefined;
```
Comment (chfritz) [inline ros/ros/ros2.js]: This could be moved in front of the if, because it is shared by both cases. But why do we need to reset it?

File: ros/ros/ros2.js [hunk 4]
```diff
@@ -137,48 +146,92 @@ class ROS2 {
...
   * */
   subscribe(topic, type, onMessage, options = {}) {
     this.requireInit();
+    let firstLatchedMessage;
     const ros2Type = toROS2Type(type);
-    const sub = this.node.createSubscription(
-      ros2Type, topic, {qos, ...options}, onMessage);
-    this.subscriptions[topic] = sub;
+    const _onMessage = options?.throttleMs ?
+      _.throttle(onMessage, options.throttleMs, { trailing: false }) :
```
Comment (chfritz) [inline ros/ros/ros2.js]: I *think* we want `trailing: true`, meaning that if there is a new value during the `throttleMs` delay, then we want that to fire at the end of the delay. But I assume you've added this for a reason. What am I missing?

File: ros/ros/ros2.js (hunk 2 above)
Comment (chfritz) [reply ros/ros/ros2.js]: Actually, yes, I remember now. We do need to keep even the "temporary" subscriber around in case it never got destroyed naturally (after receiving a message) and we call shutdown. But I'd still prefer not to make it a list. Can we make it an object `{ latchingSubscriber, volatileSubscriber }` instead?

File: ros/ros/ros2.js [hunk 5]
```diff
@@ -137,48 +146,92 @@ class ROS2 {
...
+        sub.__destroyed = true;
+        this.node.destroySubscription(sub);
+      }
+    });
+    delete this.subscriptions[topic];
   }
 
   /** Publish the given message (json) on the names topic of type. Will
   advertise the topic if not yet advertised. */
   publish(topic, type, message, latching = true) {
```
Comment (chfritz) [inline ros/ros/ros2.js]: Since until now we haven't implemented latched publishing, we should probably change this default to `false` so that for existing users nothing changes -- which is how defaults should behave, I think.

File: ros/test/ros.test.js [hunk 6]
```diff
@@ -40,15 +36,79 @@ test('loads', () => {
       expect(list.length > 0).toBeTruthy();
```
Comment (chfritz) [inline ros/test/ros.test.js:40]: How can this pass if we removed the only topic that was being published (`/utils_ros/test1`)? I suspect only by coincidence because some other ROS nodes where publishing on your system?

File: ros/ros/ros2.js (hunk 1 above)
Comment (jlurgo) [reply ros/ros/ros2.js:15]: I tried first to use it as best-effort but it didn't work, switching it to reliable made it work. I'm trying to find documentation to justify it and only found this, for RTI DDS:
https://community.rti.com/forum-topic/using-best-effort-reliability-transient-local-durability
https://community.rti.com/static/documentation/connext-dds/6.0.1/doc/api/connext_dds/api_cpp/group__DDSDurabilityQosModule.html#details

Looks like other DDS middleware implementations may support best-effort + transient-local

I'll experiment further with this

File: ros/ros/ros2.js (hunk 2 above)
Comment (jlurgo) [reply ros/ros/ros2.js]: For shutdown() it's enough to have a local variable in the subscribe() context.
But I need to keep both subscribers stored in case unsubscribe() is called before receiving any message and need to destroy both. 
I made it a list to support multiple subscribers to same topic, allowing them to be shut down independently.

Would be ok to have a list like:
```
this.subscriptions[topic] = [
{ latchingSubscriber, volatileSubscriber },
{ latchingSubscriber, volatileSubscriber },
...] 
```
??

Comment (chfritz) [reply ros/ros/ros2.js]: Seems like this is trying to do multiple things at once: add latching and allow multiple subscribers. I don't think the latter is really needed at this point. Can we decouple them?

File: ros/ros/ros2.js (hunk 5 above)
Comment (jlurgo) [reply ros/ros/ros2.js]: Sure, but what happens with ROS1 publish() should we change it to be false too?

Comment (chfritz) [reply ros/ros/ros2.js]: No, the objective is not to change the behavior of current applications. I know this is inconsistent between ROS1 and ROS2 but that's how it has been, so it's not a regression, and I don't want to change too many things at once.

File: ros/ros/ros2.js (hunk 4 above)
Comment (jlurgo) [reply ros/ros/ros2.js]: sorry, my bad, I misread documentation I was in the wrong assumption that trailing=false meant leading=true, but it's not the case. Fixing it, thanks

File: ros/test/ros.test.js (hunk 6 above)
Comment (jlurgo) [reply ros/test/ros.test.js:40]: I'm adding a pub before getTopics

File: ros/ros/ros2.js (hunk 3 above)
Comment (jlurgo) [reply ros/ros/ros2.js]: I'm using **firstLatchedMessage** variable as a flag that a message arrived first on the latching subscriber and the current message needs to be checked against it. After checking, either for true (avoid duplicating it) or for false (raise to the user code) we need to clear the flag to avoid further checking, this will happen only once.
If I move the clear line (firstLatchedMessage = undefined) before the if to avoid duplicated code I lose the content of it...

File: ros/ros/ros2.js (hunk 1 above)
Comment (jlurgo) [reply ros/ros/ros2.js:15]: No luck, having both the publisher and the subscriber with **transient-local** durability (condition to receive latched messages) I tried with all 4 combinations of pub and sub being **reliable** or **best-effort**. I only succeeded in receiving latched messages having both pub and sub ALSO being reliable

File: ros/ros/ros2.js (hunk 3 above)
Comment (chfritz) [reply ros/ros/ros2.js]: oh yes, of course, makes sense. thanks.

File: ros/ros/ros2.js (hunk 5 above)
Comment (jlurgo) [reply ros/ros/ros2.js:221]: I'll need to add a condition for ROS1 and 2 in the test case then

Comment (jlurgo) [reply ros/ros/ros2.js]: cool, will do

File: ros/ros/ros2.js (hunk 1 above)
Comment (chfritz) [reply ros/ros/ros2.js:15]: Very interesting. Good to know that not all DDSs support all the combinations specified in the QoS compatibility chart. Thanks for testing. And I assume no error or exception will be thrown when we try to subscribe with 'reliable' to a best-effort topic, correct?

By the way, for testing, in the past I used ROS 2 bags and overwrote the QoS at playback time: https://docs.ros.org/en/foxy/How-To-Guides/Overriding-QoS-Policies-For-Recording-And-Playback.html

**Comment by jlurgo** [comment]
Already tested with mock-bot/map-edit and it's working good, no more latching/throttling problems

File: ros/ros/ros2.js [hunk 7]
```diff
@@ -133,52 +142,89 @@ class ROS2 {
     return list.find(({name}) => name == service)?.types[0];
   }
```
Comment (chfritz) [inline ros/ros/ros2.js:149]: doc comment please

File: ros/ros/ros2.js [hunk 8]
```diff
@@ -133,52 +142,89 @@ class ROS2 {
...
     this.requireInit();
+    let firstLatchedMessage;
     const ros2Type = toROS2Type(type);
-    const sub = this.node.createSubscription(
-      ros2Type, topic, {qos, ...options}, onMessage);
-    this.subscriptions[topic] = sub;
+    const _onMessage = options?.throttleMs ?
+      _.throttle(onMessage, options.throttleMs) :
+      onMessage;
+
```
Comment (chfritz) [inline ros/ros/ros2.js:170]: We should add a comment here describing the approach and why we are doing this (to support latching even when we don't know whether the publisher is publishing transient-local or not).

File: ros/ros/ros2.js [hunk 9]
```diff
@@ -133,52 +142,89 @@ class ROS2 {
...
+        firstLatchedMessage = msg;
+        _onMessage(msg);
+      }
+    );
+
+    const volatileSub = this.node.createSubscription(
+      ros2Type, topic, {qos: volatileQos, ...options}, (msg) => {
+        this._destroySubscriber(latchingSub);
+        if (firstLatchedMessage){
+          if(_.isEqual(firstLatchedMessage, msg)){
```
Comment (chfritz) [inline ros/ros/ros2.js]: nit: `if(_.isEqual` -> `if (_.isEqual` (here and elsewhere); same at the end: `){` -> `) {`.

File: ros/ros/ros2.js [hunk 10]
```diff
@@ -133,52 +142,89 @@ class ROS2 {
...
+        this.unsubscribe(topic);
       }
     }
   }
 
   /** Unsubscribe from topic */
   unsubscribe(topic) {
-    const sub = this.subscriptions[topic];
-    if (!sub) {
-      console.warn(`cannot unsubscribe from ${topic}, subscription not found`);
```
Comment (chfritz) [inline ros/ros/ros2.js:160]: why remove this warning?

File: ros/ros/ros2.js [hunk 11]
```diff
@@ -133,52 +142,89 @@ class ROS2 {
...
-  publish(topic, type, message, latching = true) {
+  publish(topic, type, message, latching = false) {
     if (!this.publishers[topic]) {
       const ros2Type = toROS2Type(type);
-      this.publishers[topic] = this.node.createPublisher(ros2Type, topic);
+      if(latching){
+        this.publishers[topic] = this.node.createPublisher(ros2Type, topic, {qos: latchingQos});
+      } else {
+        this.publishers[topic] = this.node.createPublisher(ros2Type, topic, {qos: volatileQos});
+      }
```
Comment (chfritz) [inline ros/ros/ros2.js]: simpler:
```js
this.publishers[topic] = this.node.createPublisher(ros2Type, topic, {qos: latching ? latchingQos : volatileQos});
```

File: ros/test/ros.test.js [hunk 12]
```diff
@@ -13,17 +13,13 @@ test('loads', () => {
...
-    const topic = '/utils_ros/test1';
     const type = 'std_msgs/String';
 
     let ros;
     let interval;
     beforeAll(async () => {
       ros = getForVersion(version);
       await ros.init();
-      interval = setInterval(() => {
-        ros.publish(topic, type, {data: String(Date.now())});
```
Comment (chfritz) [inline ros/test/ros.test.js:25]: why do we need to remove this?

Comment (jlurgo) [reply ros/test/ros.test.js:25]: It was messing with logging when doing my new tests, but I think I can bring it back

**Comment by jlurgo** [comment]
addressed all

File: ros/docs/ros.md [hunk 13]
```diff
@@ -238,14 +238,15 @@ advertise the topic if not yet advertised.
 *   `topic` &#x20;
 *   `type` &#x20;
 *   `message` &#x20;
-*   `latching`   (optional, default `true`)
+*   `latching`   (optional, default `false`)
```
Comment (jlurgo) [inline ros/docs/ros.md:241]: hm, this was autogenerated when packing the library but defaults are different between ROS1 and 2

Comment (chfritz) [reply ros/docs/ros.md:241]: I stumbled over this, too, but it's all fine. Both ROS1 and ROS2 are documented in two separate sections in this file. You can see how this is shown on our website here: https://transitiverobotics.com/docs/sdk/ros/.

File: ros/ros/ros2.js [hunk 14]
```diff
@@ -133,52 +147,103 @@ class ROS2 {
...
+    const throttledCallback = options?.throttleMs ?
+      _.throttle(onMessage, options.throttleMs) :
+      onMessage;
+
+    // we create two subscriptions, one for latched messages and one for volatile (new) messages
+    // after receiving the first message we destroy the latched subscription and only keep the volatile one
+    // we need to do this because of qos incompatibilities between volatile/latching pubs and subs
+    // we can't have a single subscription that can handle both, and user may not be in control of the publisher
+    // see https://docs.ros.org/en/rolling/Concepts/Intermediate/About-Quality-of-Service-Settings.html#qos-compatibilities
+    const latchingSub = this.node.createSubscription(
```
Comment (chfritz) [inline ros/ros/ros2.js]: Doesn't this create a new subscriber every time `subscribe` is called? I believe we only want to do this if we have not yet subscribed to the topic in ROS. If we already have, then we only want to add the event listener to the existing emitter, and not create another pair of ROS subscribers, right?

Comment (jlurgo) [reply ros/ros/ros2.js]: That's right, fixing

Comment (jlurgo) [reply ros/ros/ros2.js]: fixed and tested

**Review by chfritz — APPROVED** [review]
